### ISSUE TITLE
Validar mapa

### ISSUE THREAD

**Issue by victor-ln** [adrianofaus/cub3D_ecole42#10]
Verificar se o mapa é válido, ou seja, uma forma totalmente cercado por paredes com espaço para colocar o player, se inclui o PATH para as texturas e escala de cores para o chão e o céu.

**Comment by victor-ln** [comment]
- [x] Validar a extensão do arquivo.
- [x] Validar se há espaço para o player (campos vazios).
- [x] Validar se inclui os paths para as quatro texturas.
- [x] Validar se há somente os caracteres permitidos.
- [x] Validar se tem apenas um player
- [x] Validar se não existem linhas vazias no conteúdo do mapa
- [x] Validar se todos os identificadores possuem somente um elemento.
- [x] Tratar espaços entre os elementos e seus identificadores.
- [x] Validar espaços vazios internos do mapa.
- [x] Validar se é cercado por paredes.
- [x] Aparar __paredes__ desnecessárias nas bordas.
- [x] Refatorar funções/Incluir na Norma
- [x] Criar testes de validação de mapa

Features adicionais:

- [ ] Validar entradas secretas.
- [ ] Validar portas.

**Comment by adrianofaus** [comment]
Testar para quando temos, linhas vazias no meio do mapa e no final do mapa.  
- Só encontramos erros quando duas bl são encontradas em seguidas e a quando a qtd de breaklines é menor ou igual q td de linhas do nosso mapa?

**Comment by adrianofaus** [comment]
- 11/07 
  - Conseguimos compilar o código e já tivemos um bom rendimento no debug, o código escrito esta quase pronto
  - Makefile está funcionando
  - Falta ajustar a save_params, pois estamos pulando todos os espaços do mapa e isso não deve acontecer

**Comment by victor-ln** [comment]
12/07
- O que fizemos:
  - [x]  Conseguimos ajustar a save_params.
  - [x]  Criamos um script para testar os erros.
  - [x]  Corrigimos o relink no Makefile.
  - [x]  Praticamente terminamos de aparar o mapa.

- O que temos para amanhã:
  - [x] Falta verificar no corpo do mapa as colunas acima e abaixo ao achar os zeros.
  - [x] Falta testar as funções que aparam o mapa.
  - [x] Verificar leaks.
  - [x] Refatorar código e colocar na norma.
