### ISSUE TITLE
Renderizar mapa sem texturas

### ISSUE THREAD

**Issue by adrianofaus** [adrianofaus/cub3D_ecole42#7]

**Comment by adrianofaus** [comment]
O mapa a ser renderizado é uma matriz normal

**Comment by adrianofaus** [comment]
13/07

- O que fizemos:
  - [x] Falta verificar no corpo do mapa as colunas acima e abaixo ao achar os zeros.
  - [x] Falta testar as funções que aparam o mapa.
  - [x] Verificar leaks.
  - [x] Refatorar código e colocar na norma.

- O que temos para amanhã:
  - [x] Assistir o curso

**Comment by victor-ln** [comment]
19/07

- O que fizemos:

  - [x] Assistimos o curso.
  - [x] Implementamos o jogo em 2D com colisão, DDA e raycasting com Javascript.
  - [x] Implementamos um primeiro esboço das estruturas que serão usadas no jogo.
  - [x] Testamos abrir e fechar uma janela com um tamanho aleatório.
 
- O que temos para amanhã:

  - [x] Importar código escrito em Javascript para C.
  - [x] Assistir módulo _Rendering walls_ do curso do Pikuma.

**Comment by adrianofaus** [comment]
20/07

- O que fizemos:

  - [x] Começamos a implementação do código do Pikuma.
  - [x] Conseguimos desenhar o mapa e o player
  - [x] Conseguimos fazer a movimentação do player
  - [x] Corrigimos bugs e leaks
 
- O que temos para amanhã:

  - [x] Terminar de importar o código escrito em Javascript para C.
  - [x] Assistir módulo _Rendering walls_ do curso do Pikuma.
